






























































}  plugins: [require("tailwindcss-animate")],  },    },      },        "fade-in": "fade-in 0.2s ease-in",      animation: {      },        },          "100%": { opacity: 1 },          "0%": { opacity: 0 },        "fade-in": {      keyframes: {      },        },          foreground: "hsl(var(--card-foreground))",          DEFAULT: "hsl(var(--card))",        card: {        },          foreground: "hsl(var(--popover-foreground))",          DEFAULT: "hsl(var(--popover))",        popover: {        },          foreground: "hsl(var(--accent-foreground))",          DEFAULT: "hsl(var(--accent))",        accent: {        },          foreground: "hsl(var(--muted-foreground))",          DEFAULT: "hsl(var(--muted))",        muted: {        },          foreground: "hsl(var(--destructive-foreground))",          DEFAULT: "hsl(var(--destructive))",        destructive: {        },          foreground: "hsl(var(--secondary-foreground))",          DEFAULT: "hsl(var(--secondary))",        secondary: {        },          foreground: "hsl(var(--primary-foreground))",          DEFAULT: "hsl(var(--primary))",        primary: {        foreground: "hsl(var(--foreground))",        background: "hsl(var(--background))",        ring: "hsl(var(--ring))",        input: "hsl(var(--input))",        border: "hsl(var(--border))",      colors: {    extend: {    },      },        "2xl": "1400px",      screens: {      padding: "2rem",      center: true,    container: {  theme: {  ],    './src/**/*.{ts,tsx}',  content: [  darkMode: ["class"],module.exports = {/** @type {import('tailwindcss').Config} */